### PR TITLE
Allow IP address to contain 255

### PR DESCRIPTION
**Pull request by joh**
Fix issue #111

### CODE REVIEW

**Comment by godsic** [comment]
@joh Thanks for fixing this issue. Have you actually tried to fix the atobyte function, instead of casting?

**Comment by joh** [comment]
@godsic Sure, I can move the casting to the atobyte function instead if you prefer?

**Comment by godsic** [comment]
@joh Sorry for not being clear. I was wondering if one can use [ParseUint](https://golang.org/pkg/strconv/#ParseUint) in atobyte(...) and then cast from uint64 to byte?

**Comment by joh** [comment]
@godsic Not sure that would make sense - the atobyte function would still need to return uint.

The problem is really the for loop at cmd/mumax3-server/main.go:191 which will cause a byte to overflow after incrementing past 255. An alternative may be to change the types of A, B, C and D to uint and leave the rest of the code as it was.

**Pull request merged**
