### PR TITLE
Inhomogeneous Msat

### PR DESCRIPTION
**Pull request by JeroenMulkers**
These changes resolve the occurring "increasing-energy" problems for samples with an inhomogeneous Msat.

- The harmonic mean A_i/M_i and A_j/M_j is no longer used as prefactor for the exchange interaction between cell i and j. Instead, the prefactor A_ij/M_i is used in cell i and A_ij/M_j in cell j.
- The default value for A_ij is the harmonic mean of A_i and A_j (arbitrary choice). 
- It is possible to rescale A_ij with `ext_ScaleExchange` (old feature).
- It is also possible to set A_ij to a specified value with `ext_InterExchange` (new feature).
- The same approach is used for the DMI.
- Simulations with homogeneous Msat before and after changes should give the same result.
- All tests run fine after minor trivial changes in test/exchcoupling.mx3 and test/dindcoupling.mx3

There is no longer a difference between aexchParam and dexchParam structs when eliminating the 1e18 and 1e9 factors in their update methods. The deduplication of these structs to a single exchParam makes to code cleaner.

### CODE REVIEW

**Comment by godsic** [comment]
@JeroenMulkers Have you tested with non-homogeneous Aex? OOMMF also does harmonic mean, so it makes sense to check against OOMMF to ensure mumax3 implementation is consistent.

**Comment by JeroenMulkers** [comment]
I did not test a non-homogeneous Aex explicitly (only through the already existing unit tests) because the changes are irrelevant for a non-homogeneous Aex.

Problems did arise for a non-homogeneous Msat. I used this [script](https://github.com/mumax/3/files/1148530/run.mx3.txt) to check if the made changes solve the increasing-energy problem. I think this script is not really suitable as a unit test due to its complexity and the long run time.

Shall I write a more simple unit test with a non-homogeneous Msat, possibly combined with a non-homogeneous Aex?

**Comment by godsic** [comment]
@JeroenMulkers Are you OK to test against OOMMF?

**Comment by JeroenMulkers** [comment]
I will give it a try.

**Comment by JeroenMulkers** [comment]
In the unit test I calculate the exchange energy for a system with an inhomogeneous Aex and Msat, and a random magnetization. The obtained numerical value corresponds exactly with the exchange energy obtained using oommf.

**Comment by godsic** [comment]
Hi Jeroen,

First of all, well done! This is impressive change set.

Would you be so kind to commit the OOMMF script and I will be happy to
merge your pull request.

Regards,
 

-----Original Message-----

Date: Wed, 19 Jul 2017 07:50:30 -0700
Subject: Re: [mumax/3] Inhomogeneous Msat (#115)
Cc: Mykola Dvornik <mykola.dvornik@gmail.com>, Review requested <review
_requested@noreply.github.com>
To: mumax/3 <3@noreply.github.com>
Reply-to: mumax/3 <reply+0023b1dbf28f459d97ef966389a45164075ab94a790598
5192cf00000001158733b692a169ce0e77ce7f@reply.github.com>
From: Jeroen Mulkers <notifications@github.com>
In the unit test I calculate the exchange energy for a system with an
inhomogeneous Aex and Msat, and a random magnetization. The obtained
numerical value corresponds exactly with the exchange energy obtained
using oommf.


—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/mumax/3","tit
le":"mumax/3","subtitle":"GitHub repository","main_image_url":"https://
cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-
95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in GitHub","url":"https://gith
ub.com/mumax/3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@J
eroenMulkers in #115: In the unit test I calculate the exchange energy
for a system with an inhomogeneous Aex and Msat, and a random
magnetization. The obtained numerical value corresponds exactly with
the exchange energy obtained using oommf."}],"action":{"name":"View
Pull Request","url":"https://github.com/mumax/3/pull/115#issuecomment-3
16412177"}}}
-Mykola

**Comment by JeroenMulkers** [comment]
Thank you. The OOMMF script is also added in commit 328a1df.

**Comment by godsic** [comment]
@JeroenMulkers Just checked the values of the exchange energy and they are consistent with yours.

**Pull request merged**
