### PR TITLE
Feature/interlayerexchange

### PR DESCRIPTION
**Pull request by tobiHZDR**
Added bilinear and biquadratic interlayer exchange coupling in x,y and z direction
Added Landau state as intial state
Saving after nbr. of steps

### CODE REVIEW

**Comment by cjermain** [comment]
What is the status of this feature?

**Comment by tobiHZDR** [comment]
Hi Colin,

The feature is finished but it won't be merged into the main code. So you have 
to recompile it on your own.
Also the version on Github is a old version of mumax.
Maybe I can include IEC into the latest version and upload it.

I tested the implementation using a FMR simulation and compared it to 
analytical calculations. The results fit perfectly.

Best,
Tobias


Am Fri, 29 May 2015 12:46:52 -0700 schrieb Colin Jermain 
<notifications@github.com>:

**Comment by cjermain** [comment]
Thanks Tobias! I will merge it with mumax3.7 and try it locally.

**Comment by barnex** [comment]
A small note on having features merged into the mainline code: the
long-term maintenance cost of a feature is often much higher than the
original effort of implementing it. In order to be maintainable on the long
term, a feature must:

* come as a pull request that can be merged without conflicts
* be implemented orthogonally to the rest of the code, as an extension
rather than modification
* be properly documented
* be accompanied by extensive automated test files, including checks for
corner cases.
* have a maintainer who promises to address any issues that might arise
with the feature.

Under these conditions, I am happy to merge features into the mainline
codebase.

-Arne.

**Comment by cjermain** [comment]
Agreed. These are good conditions -- thanks Arne! I'm happy to help with them if there is significant interest in the feature.

I was able to get the feature up and running easily by dropping the relevant files into the $GOPATH/src  MuMax3 folder and manually running make.bash followed by go install. So far the feature acts as expected and is exactly what I needed. Thanks!

**Comment by godsic** [comment]
FYI https://github.com/mumax/3/tree/feature/nonlocalRKKY

**Comment by godsic** [comment]
@cjermain would you be so kind to explain how exactly you validated the interlayer exchange implementation?

**Comment by cjermain** [comment]
Sure, @godsic. I tested and used this feature on a perpendicularly-magnetized magnetic tunnel junction (MTJ) with synthetic antiferromagnet (SAF) (3 magnet layers) -- the results of which have not been published. When I first installed it, I did not add the interlayer-exchange field to the effective field properly (I was missing corrections to engine/effectivefield.go), so I noticed that the feature was having no effect. Once I got that fixed, I tested it on a few simulations where I varied the IEC coupling. I looked at comparison between the exchange rescale feature and the IEC feature to see the differences. 

I would recommend using just a 2 magnet system for your test, where you can solve the problem in the macrospin limit. If you make the layers adjacent, you may be able to compare the exchange rescale to the IEC feature by rescaling the exchange to 0 for the IEC test.

**Comment by godsic** [comment]
@cjermain Do you have some example mx3 scripts / references?

**Comment by cjermain** [comment]
@godsic, its best if you make your own given the recommendations I made. The scripts I have from last May are not good general tests.

**Pull request closed without merging**
