### PR TITLE
ext_CenterWall per region

### PR DESCRIPTION
**Pull request by jsampaio**
This change adds ext_centerWallInRegion(R,c), which works like ext_centerWall but only for a specified region. This is useful for simulating SAFs, for example.

### CODE REVIEW

**Comment by godsic** [comment]
@jsampaio would you be so kind to clean this up?

**Comment by godsic** [comment]
@jsampaio Also, have you tried to run unit tests?

**Comment by godsic** [comment]
@jsampaio if you want this merged, then please cleanup and resolve conflicts.

**Comment by jsampaio** [comment]
@godsic : I'll look into it again. I think the changes I did to add ext_centerWallInRegion(R,c) got mixed in with other (unrelated) changes to the code...

**Comment by jsampaio** [comment]
@godsic I cleaned it up a bit and added a new option for shifting the magnetisation that uses the current values at the border for the new cells introduced by shift. This mode is more useful for simulations of antiparallel coupled layers (SAF like in the RKKY example). Because of the clean-up, I had to do a new branch, and so I'll do a new pull request.

**Pull request closed without merging**
