### PR TITLE
Feature/customexchange

### PR DESCRIPTION
**Pull request by JLeliaert**
I slightly edited engine/customfields.go to add an Add function for quantities and fix a typo/bug in Shifted.

With this new functionality I wrote a custom_exchange.mx3 test identical to the original exchange.mx3 test, but with the exchange defined as a custom field.

### CODE REVIEW

**Comment by godsic** [comment]
does it pass all the unit tests?

**Comment by JeroenMulkers** [comment]
Yes

**Comment by godsic** [comment]
Commits are still coming. Is it really stable for merging?

**Comment by JeroenMulkers** [comment]
I think it is ready to be merged. But let's wait for @JLeliaert 's approval.

**Pull request merged**
